-- CyberpunkVRPort — the hands, their FINGERS, and the weapon they hold all stop at the body and at each other.
--
-- WHY NOT PHYSICS. Every collider involved is Kinematic: the body capsules, the hand capsules, the weapon's
-- cooked bodies. A kinematic body pushes DYNAMIC objects -- which is why props and the ball work -- but nothing
-- pushes it, and two kinematic bodies do not interact at all. Masks decide whether a contact is generated;
-- simulationType decides whether anything MOVES. Dynamic is not available either, measured three ways:
-- authored Dynamic the capsule is not held by its bone binding and fell to Z = -8100; flipped live the flip is
-- ONE-WAY (kin=1 while 1519 m away at 110 m/s); and SetTransform is inert -- four different local positions all
-- left the world bounds identical.
--
-- So the hand is stopped by moving the arm solver's TARGET. Verified end to end: a forced 10 cm hold put the
-- solved palm exactly 0.080 m below the tracked target -- the commanded 0.10 minus the then-0.02 deadband. An
-- earlier attempt did nothing because the clamp sat before the gizmo path, which recomputes target[0..2]; it now
-- runs immediately before VRIK_SolveArm. And the bone snapshot only exists while SetVRDiagCapture is on, which is
-- why the attempt before that found no capsules at all.
--
-- WHAT MOVES, AND WHAT THAT MEANS. The only handle is the wrist target, so the thing being solved is a RIGID
-- TRANSLATION of everything that rides that wrist: the palm, all fifteen phalanges, and every capsule of the
-- weapon in that hand. Press the muzzle into your chest and the whole gun slides back rather than pivoting about
-- the grip -- a real gun would rotate, but rotation is not ours to give, and a slide is the honest approximation.
-- A fingertip stopping the hand is the same statement: the arm cannot reach further because a finger is against
-- something, so the wrist ends up where that finger's contact leaves it.
--
-- THE GEOMETRY IS NOT RETYPED HERE. capsules.lua is generated by tools/emit_hand_collision_data.py from the very
-- SEGMENTS and FINGER_SEGMENTS tables that write the .ent, placement rules included. So what stops a hand and
-- what a ball bounces off cannot disagree.
--
-- The PALM is deliberately a different size for the two jobs, and the generator holds both numbers with the
-- reason. For props the collider is a 0.16 m tube down the whole hand -- a ball should bounce off a hand, not
-- fall between its fingers. Here the fingers exist, and a 0.16 m tube with a 31 mm radius swallows every one of
-- them, which is why fingers "did not collide" even once they were in the table. So the clamp gets the rigid palm
-- instead: 0.0814 m, the measured wrist-to-Middle1 distance.
--
-- EVERYTHING IS MODEL SPACE: bones come from VRBoneModelPos/Rot there, and VRHandRawModel / VRHandStopModel keep
-- the target there, so no frame conversion happens anywhere.
--
-- ============================================================================================================
-- THE SHAKE, AND EVERY CAUSE IT TURNED OUT TO HAVE
--
-- Five rounds of "it still twitches", five different causes. Worth listing, because four of them look identical
-- in the headset and none of them was noise:
--
--   1. FEEDBACK. The resolved position is a function of the obstacle geometry, and some of that geometry is
--      placed by the very solve this target drives. vrp_arm_<side> was an obstacle for its own hand, and
--      VRIK_SolveArm places the upper arm, forearm AND hand from one target, so pushing the hand swept the
--      shoulder capsule. Also: a shape oriented by the solved bone, and the holder chosen per frame as "nearer
--      wrist" -- a coin flip at the grip, and each flip swapped which hand was frozen.
--   2. A CAPSULE THAT WAS NOT THE GUN. The frame bone's fit came out as a 0.0725 m radius ball at the grip,
--      against a weapon 0.027 half-thick, so the free hand was shoved 0.113 m clear of the pistol. Fixed in the
--      decomposition (tools/emit_weapon_collision_data.py), not here.
--   3. WINNER-TAKES-ALL. Applying only the deepest contact per pass made the answer depend on which of a dozen
--      contacts won, and the winner changed every frame: the hold jumped between 0.042 and 0.113 m.
--   4. AVERAGING. Fixed the jump but divided the correction by the contact count, so the stop got softer the
--      more capsules were involved -- twenty at a gun -- and the hand sank through. Reported exactly as
--      "collision comes and goes". Sequential projection is count-independent and is what runs now.
--   5. GARBAGE COLLECTION. With none of the above left, the timing said mean 2.36 ms, worst mean 4.38, and
--      single frames at 16-22 ms with only 19 pairs in them. At 45 fps the whole frame is 22 ms, so those were
--      dropped frames, and a dropped frame reads as a twitch on whatever you are looking at. The cause was this
--      module allocating roughly a thousand tables a frame -- a capsule record plus two endpoint tables each, a
--      table per candidate pair, and a CONCATENATED STRING key per pair. Everything below is pooled and flat for
--      that reason: capsules are tables of scalars taken from a pool, the candidate list is parallel arrays, and
--      contact keys are integers.
--
-- The ORDER of the two solves keeps the weapon out of the feedback. The holder resolves first, from its RAW
-- wrist, against the body -- a pure function of tracking. The free hand resolves second, against the gun placed
-- where the holder's solve just put it. One direction, no cycle. The free hand never displaces the holder: it
-- sees the holder's hand and gun as immovable, which is also what a hand pressing on a braced gun feels like.
--
-- Plus one thing that was not a shake but made all of them worse: the plugin's 0.02 m deadband applied only
-- (len - dead)/len of the hold, so a 3 cm push became 1 cm and the drawn hand always sat up to 2 cm INSIDE
-- whatever stopped it. That belongs to the abandoned velocity-driven design, where a driven body genuinely
-- trailed its target. This resolution is analytic and exact, so the deadband is pure error.
-- ============================================================================================================

-- DEBUG LOGGING, one flag for every CET bridge: the plugin publishes the launcher's DEBUG state to
-- shared slot [156]. Without it these per-second reports produced megabytes a session for users who
-- never asked for them -- measured 3.4 MB from this mod alone in one sitting. Nothing is deleted: tick
-- DEBUG and every line comes back.
local function dbgOn()
    if type(GetVRSharedSlot) ~= 'function' then return false end
    return GetVRSharedSlot(156) > 0.5
end

local CAPS = require('capsules')

local HAND_SLOT = { [0] = 'vrp_hand_l', [1] = 'vrp_hand_r' }
local FORE_SLOT = { [0] = 'vrp_fore_l', [1] = 'vrp_fore_r' }
local ARM_SLOT  = { [0] = 'vrp_arm_l',  [1] = 'vrp_arm_r' }

local PASSES   = 10      -- sweeps over the contact list; with OMEGA 0.6 a lone contact is 99.4% gone by 10
local SETTLED  = 3e-4    -- m, stop sweeping once nothing is deeper than this
local OMEGA    = 0.6     -- how much of each contact's correction is taken per visit; under 1 for stability
local DEAD     = 0.002   -- under this the hand is where tracking wants it; publish no hold
local MAX_HOLD = 0.40    -- m, how far the drawn hand may lag the real one before the hold is given up
local RELEASE  = 0.15    -- s, how long giving it up takes, so the hand slides back instead of snapping
local BROAD    = 0.02    -- m, pairwise slack; that list is rebuilt when the rig drifts half of it
local CULL     = 0.15    -- m, slack on the coarse cull: it is built once, so it must survive the whole hold
local RELEASE_MARGIN = 0.006   -- m of clearance before a contact lets go; without it contact flickers at the
                               -- surface every frame, which is felt as shaking

-- STICKY EXIT DIRECTION, per side per (mover, obstacle) pair, keyed by INTEGER -- see cause 5.
-- Without it a mover pops out the far side of a capsule as soon as it is pushed past the axis: the shortest way
-- out flips, and what you see is the hand teleporting through the chest after a centimetre or two.
local stick = { [0] = {}, [1] = {} }
local fade  = { [0] = 0.0, [1] = 0.0 }

-- THE BODY CAPSULES MUST NOT ANSWER QUERIES EITHER, and not on a lazy timer. A character controller moves by
-- sweeping scene queries, and every VRPortBody_ capsule overlaps its 0.25 m cylinder -- hands by 0.036 m, the torso
-- by 0.34 -- so a queryable capsule is the controller standing inside geometry, which the engine answers by pushing
-- the player UP. That is the twitch on jump and landing: the capsules re-register on a state change and come back
-- queryable, and a half-second window of that is a shove.
--
-- Every frame, then, not every 0.5 s, and from THIS module so it does not depend on the basketball mod being on.
-- Sixteen guarded calls a frame cost nothing measurable next to the solve.
local bqBodies, bqScanAt = nil, -1.0

local function bodyQueriesOff(now)
    if not bqBodies or now - bqScanAt > 5.0 then
        local pl = Game.GetPlayer()
        if not pl then return end
        local found = {}
        local ok = pcall(function()
            local cs = pl:GetComponents()
            for i = 1, #cs do
                if string.find(tostring(cs[i]:GetName()), 'VRPortBody_') then
                    local b = cs[i]:CreatePhysicalBodyInterface(0)
                    if b then found[#found + 1] = b end
                end
            end
        end)
        -- SAY what the scan found. "Still twitches" means nothing until it is known whether these bodies exist,
        -- whether they answer, and whether the call is accepted -- the weapon's pass looked identical and turned out
        -- to be finding zero bodies.
        if dbgOn() then
            pcall(function() spdlog.info(string.format('[BodyQuery] %d capsule bodies found', #found)) end)
        end
        if not ok or #found == 0 then return end
        bqBodies, bqScanAt = found, now
    end
    for i = 1, #bqBodies do
        if not pcall(function() bqBodies[i]:SetIsQueryable(false) end) then
            pcall(function() spdlog.info('[BodyQuery] SetIsQueryable REJECTED on capsule ' .. i) end)
            bqBodies = nil                 -- stale handles after a reload: rescan next tick
            return
        end
    end
end

-- A CAR IS GEOMETRY THE PLAYER SITS INSIDE, AND THE CAPSULES GO IN WITH THEM.
--
-- Queries off is not enough here. It hides the capsules from the MOVEMENT system, which is what stopped the player
-- climbing over their own gun, but it leaves the simulation contacts -- and those are the point, they are what makes
-- props bounce off the body. On foot that is right. Mounted, the body is parked inside the seat, the door and the
-- dashboard, so every one of those contacts is an interpenetration the solver has to resolve; the player is carried
-- by the vehicle and cannot move, so the only thing left to push is the vehicle. Hence a car that leaves the ground
-- the moment you get in.
--
-- The capsules come from the ARCHIVE, not from this module, so turning the collision solve off does not remove them
-- (the same reason the weapon stays physical with COLL_ON false). They have to be switched off on the components
-- themselves, and back on when the player gets out.
--
-- Handles do not survive the toggle, so the queries-off scan is invalidated with it.
--
-- CAPS_PHYS_ON is the same switch used as a bisect handle: false keeps the capsules off everywhere, not just in a
-- vehicle, which is how "are the body capsules behind this crash" gets answered without touching the archive. The
-- archive is 18 MB of weapon meshes, poses and effects and the only no-capsule build of it is ten days old, so
-- swapping archives would change far more than the thing under test.
local CAPS_PHYS_ON = false

local vbComps, vbScanAt, vbWanted = nil, -1.0, nil

local function bodyCapsulesForVehicle(now)
    local inCar = false
    pcall(function()
        local pl = Game.GetPlayer()
        if pl then inCar = Game.GetMountedVehicle(pl) ~= nil end
    end)
    local want = CAPS_PHYS_ON and not inCar
    if vbWanted == want then return inCar end
    if not vbComps or now - vbScanAt > 5.0 then
        local found = {}
        pcall(function()
            local pl = Game.GetPlayer()
            if not pl then return end
            local cs = pl:GetComponents()
            for i = 1, #cs do
                if string.find(tostring(cs[i]:GetName()), 'VRPortBody_') then found[#found + 1] = cs[i] end
            end
        end)
        if #found == 0 then return inCar end
        vbComps, vbScanAt = found, now
    end
    for i = 1, #vbComps do pcall(function() vbComps[i]:Toggle(want) end) end
    vbWanted = want
    bqBodies = nil
    pcall(function() spdlog.info(string.format('[BodyCaps] %s (%d capsules)',
        want and 'ON' or 'OFF -- mounted', #vbComps)) end)
    return inCar
end

-- THE WEAPON MUST NOT ANSWER SCENE QUERIES. Its parts were made physical so they push props, and that also put them
-- in front of the player as something the MOVEMENT system can see: a character controller moves by sweeping queries,
-- so a gun held at chest height is a wall to walk into and a ledge to mantle over ("упирается при ходьбе, при прыжке
-- перелезает"). Queries off keeps the simulation contacts -- props still bounce off the gun -- and hides it from
-- movement. The same fix already stopped the player climbing over the basketball and the body capsules.
--
-- On a timer, not once: a weapon that is drawn, holstered or swapped comes back queryable, and one queryable frame at
-- chest depth is a shove.
local wqBodies, wqKey, wqAt = nil, nil, -1.0

local function weaponQueriesOff(weapon, now)
    if not weapon then wqBodies, wqKey = nil, nil; return end
    local okK, key = pcall(function() return tostring(weapon:GetEntityID().hash) end)
    if not okK then return end
    -- wqKey == key with no list means "asked already, this weapon has none" -- see the cache note below.
    if wqKey == key and not wqBodies then return end
    if wqKey ~= key or not wqBodies then
        local found = {}
        local ok = pcall(function()
            local cs = weapon:GetComponents()
            for i = 1, #cs do
                if string.find(tostring(cs[i]:GetClassName()), 'Physical') then
                    local b = cs[i]:CreatePhysicalBodyInterface(0)
                    if b then found[#found + 1] = b end
                end
            end
        end)
        -- SAY how many bodies answered. "Queries off did not help" has two very different causes -- the call not
        -- landing at all, or landing and not being what blocks the player -- and only this tells them apart.
        if dbgOn() then
            pcall(function()
                spdlog.info(string.format('[WeaponQuery] weapon %s: %d physical bodies found', key, #found))
            end)
        end
        if not ok or #found == 0 then
            -- REMEMBER THE NEGATIVE ANSWER. Returning without caching meant this whole scan ran again
            -- next frame, and logged again: 34126 lines in one session, and a component walk per frame
            -- for a weapon that will never have physical bodies. The key is stored with an empty list,
            -- so the scan happens once per weapon and the retry comes with the next weapon.
            wqBodies, wqKey = nil, key
            if dbgOn() then
                pcall(function() spdlog.info('[WeaponQuery] NO physical bodies on this weapon') end)
            end
            return
        end
        wqBodies, wqKey, wqAt = found, key, -1.0
    end
    if now - wqAt < 0.5 then return end
    wqAt = now
    for i = 1, #wqBodies do
        if not pcall(function() wqBodies[i]:SetIsQueryable(false) end) then
            pcall(function() spdlog.info('[WeaponQuery] SetIsQueryable REJECTED on body ' .. i) end)
            wqBodies, wqKey = nil, nil     -- stale handles after a redraw: rescan next tick
            return
        end
    end
end

local SMOOTH_TAU = 0.040
local smooth   = { [0] = nil, [1] = nil }
local lastStep = { [0] = nil, [1] = nil }
local flips    = { [0] = 0, [1] = 0 }
local worstM   = { [0] = '-', [1] = '-' }   -- the deepest contact, named, so a bad capsule can be found
local worstS   = { [0] = '-', [1] = '-' }
local candMax  = 0
local msAcc, msMax, msN = 0.0, 0.0, 0

-- ---------------------------------------------------------------------------------------------------------
-- POOLED, FLAT SCRATCH, allocated once and reused for the session. A capsule is one table of scalars rather
-- than a table holding two endpoint tables; the candidate list is parallel arrays rather than a table per pair.
-- See cause 5: this mattered more than any of the maths above it.

local POOL, poolN = {}, 0

local function cap(id, r, ax, ay, az, bx, by, bz, label)
    poolN = poolN + 1
    local c = POOL[poolN]
    if not c then c = {}; POOL[poolN] = c end
    c.id, c.r, c.label = id, r, label
    c.ax, c.ay, c.az, c.bx, c.by, c.bz = ax, ay, az, bx, by, bz
    c.cx, c.cy, c.cz = (ax + bx) * 0.5, (ay + by) * 0.5, (az + bz) * 0.5
    local dx, dy, dz = bx - ax, by - ay, bz - az
    c.e = math.sqrt(dx * dx + dy * dy + dz * dz) * 0.5 + r
    return c
end

-- Two reusable capsule lists are enough: no step needs three at once, and hand-against-hand needs exactly two.
local LA, LB = { n = 0 }, { n = 0 }
local NEAR = { n = 0 }
local CD_M, CD_S, CD_KEY = {}, {}, {}

local function push(l, c) local k = l.n + 1; l.n = k; l[k] = c end

-- Bone poses, read once per bone per frame: the riding sets and the obstacle lists touch the same bones several
-- times a frame, and every VRBoneModelPos/Rot call crosses into the plugin and hands back fresh userdata.
local BPX, BPY, BPZ, BQI, BQJ, BQK, BQR, BGEN, BOK = {}, {}, {}, {}, {}, {}, {}, {}, {}
local gen = 0

local function bone(idx)
    if BGEN[idx] == gen then
        if not BOK[idx] then return nil end
        return BPX[idx], BPY[idx], BPZ[idx], BQI[idx], BQJ[idx], BQK[idx], BQR[idx]
    end
    BGEN[idx] = gen
    local p = VRBoneModelPos(idx)
    local q = VRBoneModelRot(idx)
    if not p or p.w < 0.5 or not q then BOK[idx] = false return nil end
    BOK[idx] = true
    BPX[idx], BPY[idx], BPZ[idx] = p.x, p.y, p.z
    BQI[idx], BQJ[idx], BQK[idx], BQR[idx] = q.i, q.j, q.k, q.r
    return BPX[idx], BPY[idx], BPZ[idx], BQI[idx], BQJ[idx], BQK[idx], BQR[idx]
end

local function qrot(qi, qj, qk, qr, x, y, z)
    local tx = 2.0 * (qj * z - qk * y)
    local ty = 2.0 * (qk * x - qi * z)
    local tz = 2.0 * (qi * y - qj * x)
    return x + qr * tx + (qj * tz - qk * ty),
           y + qr * ty + (qk * tx - qi * tz),
           z + qr * tz + (qi * ty - qj * tx)
end

-- ---------------------------------------------------------------------------------------------------------

-- World -> model through the PLAYER's transform. NOT VRWorldToModel: that is anchored on the render-view pair,
-- and VRViewWorldPos sits about a metre below the real camera, which put the gun 0.397 m from the hand holding
-- it. A round trip through it is exact because both directions share the error, so it looked fine. Measured
-- replacement: world = playerPos + playerRot * model, which predicted the hand capsule's own world centre to
-- 0.081 m -- exactly its authored offset from the wrist -- and the gun to 0.072 m from the hand.
-- Returned as SCALARS, and the rotation is done by qrot rather than Quaternion.Transform: that call allocates a
-- Vector4 in and a Vector4 out, and with 58 weapon capsules converted twice each it was another 200-odd userdata
-- a frame feeding the collector -- the same cause 5 as the Lua tables.
local function worldFrame()
    local pl = Game.GetPlayer()
    if not pl then return nil end
    local ok, base = pcall(function() return pl:GetWorldPosition() end)
    if not ok or not base then return nil end
    local ok2, q = pcall(function() return pl:GetWorldOrientation() end)
    if not ok2 or not q then return nil end
    return base.x, base.y, base.z, -q.i, -q.j, -q.k, q.r    -- conjugate: world -> model
end

-- THE WEAPON, PART BY PART.
--
-- Its collision is a cooked triangle mesh per moving part, and those parts live on the WEAPON's own rig -- which
-- the player's bone snapshot does not reach, covering 95 player bones. The way in is SLOTS: a slot bound to a
-- part's bone reports that bone's live world transform to script, and moves when the part moves. Measured on the
-- Silverhand: FX_slots/Muzzle sits 0.283 m from the gun origin, exactly the barrel's length, and
-- fx_ejection_port at 0.097 m, on the slide. The appearance carries a vrp_<bone> slot per part.
local WCAPS = nil
do
    local ok, t = pcall(function() return require('weapon_silverhand') end)
    if ok then WCAPS = t end
end

-- PHYSICAL RELOAD, hand-driven: MOVED OUT to its own CET mod, CyberpunkVRPort_Reload. It was built here and
-- lived in a reload/ sub-directory, but the two are different jobs on one pair of hands -- this module pushes the
-- hands OUT of geometry, the reload holds one hand ON a weapon part -- and while they shared a folder they had to
-- share this one onUpdate as well. What still crosses is the wrist the reload owns, in shared slot [162].

-- Collision master switch. OFF while the reload is being developed so the free hand can move to the slide/mag
-- without the body-collision solve nudging it (which reads as a twitch). Flip to true and redeploy to re-enable.
-- (No console toggle: CET's sandbox exposes neither `_G` nor `package`, and touching either crashes init.lua.)
local COLL_ON = false

local slotComp, slotEnt = nil, nil

-- HOLD ON TO THE WEAPON ONCE FOUND. GetActiveWeapon() is not reliable frame to frame: measured in one session it
-- answered with 58 capsules at 23:32 and nothing at all at 23:36 with the gun still in hand, and it had already
-- answered "no weapon" several times during this work while a pistol was plainly held. Re-resolving every frame
-- therefore drops the weapon's collision at random, and it is what made the rig census record nothing.
--
-- So the last weapon is kept and re-validated cheaply -- can its world position still be read -- and only given
-- up after a run of failures, which is what holstering actually looks like.
local lastW, wMiss = nil, 0
local W_GIVE_UP = 30       -- frames of failure before the weapon is considered gone (~0.7 s at 45 fps)

local function heldWeapon()
    local pl = Game.GetPlayer()
    if not pl then lastW, wMiss = nil, 0 return nil end
    local ok, w = pcall(function() return pl:GetActiveWeapon() end)
    if ok and w then
        lastW, wMiss = w, 0
        return w
    end
    if lastW then
        -- still there? a held entity answers for its position; a despawned one does not
        local ok2, p = pcall(function() return lastW:GetWorldPosition() end)
        if ok2 and p then
            wMiss = wMiss + 1
            if wMiss < W_GIVE_UP then return lastW end
        end
        lastW, wMiss = nil, 0
    end
    return nil
end

-- THE WEAPON'S OWN RIG, armed for the physical reload. The parts of a gun -- magazine, slide, hammer -- are moved
-- by the weapon's animation and nothing in script can touch them, but the plugin's pose hook runs on EVERY
-- skeleton's apply and can write parent-local transforms. VRWeaponRigArm points it at this weapon's skeleton the
-- same way the player's is armed. This is a READ for now: if the slide's local translation is seen to move while a
-- vanilla reload plays, then writing it is possible by construction.
--
-- Slot order is fixed by the plugin: mag_std, front_slider, back_slider, rotator, weapon_trigger, hammer, bullet,
-- bullet_reload, barrel.
local RIG_PARTS = { 'mag_std', 'front_slider', 'back_slider', 'rotator', 'weapon_trigger',
                    'hammer', 'bullet', 'bullet_reload', 'barrel' }
local rigEnt, rigFound, rigVia, rigOff = nil, -1, '-', -1
local censusAt = nil
local censusStarted = false
local WGX, WGY, WGZ, WGDX, WGDY, WGDZ, WGN = {}, {}, {}, {}, {}, {}, 0
-- The weapon ENTITY's own origin, in model space. This is the grip: measured, it sits 0.072 m from the wrist
-- holding it. It is NOT taken from a capsule any more -- capsule 1 used to be the grip slice back when the frame
-- bone was cut into three, but the recursive decomposition emits chunks in traversal order, so capsule 1 can be
-- anywhere on the gun, including the muzzle. A muzzle is far from both hands, and while aiming the LEFT one is
-- often nearer, so the holder latched to the wrong hand and the solver then spent every frame shoving the hand
-- that actually holds the pistol off its own pistol. In the log: "stopped by R = vrp_hand_r>barrel".
local WGRX, WGRY, WGRZ = 0.0, 0.0, 0.0

-- Reads the live slots into the flat arrays above, in MODEL space. Returns the count, 0 if there is no weapon.
local function readWeapon()
    WGN = 0
    if not WCAPS then return 0 end
    local pl = Game.GetPlayer()
    if not pl then return 0 end
    local w = heldWeapon()
    if not w then slotComp, slotEnt = nil, nil return 0 end
    local bx, by, bz, ii, ij, ik, ir = worldFrame()
    if not bx then return 0 end

    local key = tostring(w:GetEntityID().hash)
    if key ~= slotEnt then slotComp, slotEnt = nil, key end
    if key ~= rigEnt then
        rigEnt = key
        rigFound, rigVia, rigOff = -1, '-', -1
        -- IDENTIFY THE WEAPON'S RIG BY CENSUS, not by searching memory.
        --
        -- Disassembling the pose function settled that it is a remap copy serving SEVERAL rigs, with the fourth
        -- argument selecting the remap table -- and the hook already receives that argument. So the hook records
        -- every (trackBuf, a4) it sees that is not the player's, and the entries that appear when a weapon is
        -- drawn are the weapon's four rigs. Recording arguments is safe; the previous attempt walked a
        -- component's memory looking for the rig and crashed the game.
        --
        -- The bone indices need no search either: they come from the rig assets, read offline.
        --   frame rig    0 barrel_plug 1 barrel 2 muzzle_slot 3 fx_muzzle 4 pos_ironsight 5 front_slider
        --                6 back_slider 7 safelock 8 mag_slot 9 bullet_pull 10 bullet 11 bullet_reload
        --                12 hammer 13 rotator 14 ammo_mover 15 weapon_trigger
        --   magazine rig 0 mag_plug 1 magazine 2 magazine_reload 3 mag_std 4 mag_stdr
        censusAt = 0.0
        -- NOT reset here. Resetting at the draw is what made the flag useless: every entry after it, environment
        -- rigs included, was stamped "born with a weapon out" and total=28 born=28 said nothing. The census starts
        -- with the module instead, so whatever appears once a gun is drawn stands out on its own.
    end

    -- RESOLVE THE SLOT COMPONENT BY ASKING. A weapon carries several: measured, UI_Slots and SlotComponent both
    -- answer found=false for these slots and only FX_slots answers, so the right one is the one that does.
    --
    -- This block was accidentally cut by an edit to the census code above, and the symptom was misleading: every
    -- part failed to resolve, WGN came out 0, and the log printed gun=0 -- which reads as "no weapon in hand" and
    -- sent me looking at GetActiveWeapon, which was innocent. The log now separates the two.
    if not slotComp then
        local cs = w:GetComponents()
        for i = 1, #cs do
            if string.find(tostring(cs[i]:GetClassName()), "SlotComponent") then
                local o, found = pcall(function() return cs[i]:GetSlotTransform(CName.new(WCAPS[1].slot)) end)
                if o and found then slotComp = cs[i] break end
            end
        end
        if not slotComp then return 0 end
    end

    local n = 0
    for i = 1, #WCAPS do
        local c = WCAPS[i]
        local o, found, tr = pcall(function() return slotComp:GetSlotTransform(CName.new(c.slot)) end)
        if o and found and tr then
            local wp = nil
            pcall(function() wp = WorldPosition.ToVector4(tr.Position) end)
            local q = tr.Orientation
            if wp and q then
                -- authored in the bone's frame: rotate into the world, then convert into model space
                local ox, oy, oz = qrot(q.i, q.j, q.k, q.r, c.cx, c.cy, c.cz)
                local axw, ayw, azw = qrot(q.i, q.j, q.k, q.r, c.ax, c.ay, c.az)
                local mx, my, mz = qrot(ii, ij, ik, ir, wp.x + ox - bx, wp.y + oy - by, wp.z + oz - bz)
                local dx, dy, dz = qrot(ii, ij, ik, ir, axw, ayw, azw)
                n = n + 1
                WGX[n], WGY[n], WGZ[n] = mx, my, mz
                WGDX[n], WGDY[n], WGDZ[n] = dx * c.half, dy * c.half, dz * c.half
            end
        end
    end
    WGN = n
    return n
end

local capOn = false
local function ensureCapture()
    if capOn then return end
    if pcall(function() SetVRDiagCapture(1) end) then capOn = true end
end

-- Cut the plugin's deadband to the module's own threshold, so the hold published is the hold applied.
local deadSet = false
local function ensureDeadband()
    if deadSet then return end
    if type(VRHandStopDeadband) ~= 'function' then return end
    if pcall(function() VRHandStopDeadband(DEAD) end) then deadSet = true end
end

-- A capsule's two model-space endpoints, as six scalars. ox/oy/oz overrides the bone's own position.
local function endpoints(c, ox, oy, oz)
    local px, py, pz, qi, qj, qk, qr = bone(c.index)
    if not px then return nil end
    local bx, by, bz = ox or px, oy or py, oz or pz
    local xx, xy, xz = qrot(qi, qj, qk, qr, 1.0, 0.0, 0.0)
    local yx, yy, yz = qrot(qi, qj, qk, qr, 0.0, 1.0, 0.0)
    local zx, zy, zz = qrot(qi, qj, qk, qr, 0.0, 0.0, 1.0)
    local cx = bx + xx * c.cx + yx * c.cy + zx * c.cz
    local cy = by + xy * c.cx + yy * c.cy + zy * c.cz
    local cz = bz + xz * c.cx + yz * c.cy + zz * c.cz
    local h = c.half
    return cx - xx * h, cy - xy * h, cz - xz * h,
           cx + xx * h, cy + xy * h, cz + xz * h
end

-- Closest points between two segments, all scalars: clamped solve plus the refinement pass that makes it correct
-- when the nearest approach lands on an endpoint.
local function segClosest(pax, pay, paz, pbx, pby, pbz, qax, qay, qaz, qbx, qby, qbz)
    local ux, uy, uz = pbx - pax, pby - pay, pbz - paz
    local vx, vy, vz = qbx - qax, qby - qay, qbz - qaz
    local wx, wy, wz = pax - qax, pay - qay, paz - qaz
    local a = ux * ux + uy * uy + uz * uz
    local b = ux * vx + uy * vy + uz * vz
    local c = vx * vx + vy * vy + vz * vz
    local d = ux * wx + uy * wy + uz * wz
    local e = vx * wx + vy * wy + vz * wz
    local den = a * c - b * b
    local sc = 0.0
    if den > 1e-9 then sc = (b * e - c * d) / den end
    if sc < 0.0 then sc = 0.0 elseif sc > 1.0 then sc = 1.0 end
    local tc = 0.0
    if c > 1e-9 then
        tc = (e + b * sc) / c
        if tc < 0.0 then tc = 0.0 elseif tc > 1.0 then tc = 1.0 end
    end
    if a > 1e-9 then
        sc = (b * tc - d) / a
        if sc < 0.0 then sc = 0.0 elseif sc > 1.0 then sc = 1.0 end
    end
    return pax + ux * sc, pay + uy * sc, paz + uz * sc,
           qax + vx * tc, qay + vy * tc, qaz + vz * tc
end

-- Finger capsules: slot named vrp_f_<finger><joint>_<l|r>.
local function fingerSide(slot)
    if slot:sub(1, 6) ~= 'vrp_f_' then return nil end
    local tail = slot:sub(-2)
    if tail == '_l' then return 0 elseif tail == '_r' then return 1 end
    return nil
end

-- Which body capsules may stop the rig hanging off the wrist of `side`. Excluded: everything that wrist's own IK
-- places -- upper arm, forearm, hand -- because a capsule that moves when the wrist is pushed is a feedback loop
-- (cause 1). And every hand and finger capsule of EITHER side, because they all hang off a hand bone that carries
-- a clamp; those come back through ridingSet, placed from a raw target instead.
local OBST, HAND, RIDE = {}, {}, {}
for side = 0, 1 do
    OBST[side] = { n = 0 }
    RIDE[side] = { n = 0 }
    for i = 1, #CAPS do
        local c = CAPS[i]
        c.uid = i
        if c.slot ~= ARM_SLOT[side] and c.slot ~= FORE_SLOT[side]
           and c.slot ~= HAND_SLOT[0] and c.slot ~= HAND_SLOT[1]
           and fingerSide(c.slot) == nil then
            push(OBST[side], c)
        end
        if c.slot == HAND_SLOT[side] then HAND[side] = c end
        if c.slot == HAND_SLOT[side] or fingerSide(c.slot) == side then push(RIDE[side], c) end
    end
end

-- Contact ids: a body or finger capsule takes its index in CAPS, a gun capsule 100 + its index. The pair
-- (mover, obstacle) tells the roles apart, so the same capsule may appear as both. Integers rather than
-- concatenated strings -- one string per candidate pair was hundreds of allocations a frame.
local GUN_ID = 100

local function buildObstacles(side, out)
    out.n = 0
    local list = OBST[side]
    for i = 1, list.n do
        local c = list[i]
        local ax, ay, az, bx, by, bz = endpoints(c)
        if ax then push(out, cap(c.uid, c.r, ax, ay, az, bx, by, bz, c.slot)) end
    end
    return out
end

-- The palm and every phalanx of `side`, as they would sit with that wrist at x,y,z.
--
-- EXACT rather than an approximation: the finger bones are descendants of the hand bone, so the whole set is
-- rigid with respect to the wrist, and the clamp only ever TRANSLATES the wrist. The set as measured now, moved
-- by (x,y,z) minus the hand bone's position, IS the set with the wrist at x,y,z -- and that subtraction cancels
-- whatever hold was active when the bones were read. So finger geometry stays a function of tracking and of the
-- animated curl, never of last frame's output. The curl matters: a closed fist collides as a fist.
local function ridingSet(side, x, y, z, out)
    local h = HAND[side]
    if not h then return out end
    local hx, hy, hz = bone(h.index)
    if not hx then return out end
    local dx, dy, dz = x - hx, y - hy, z - hz
    local list = RIDE[side]
    for i = 1, list.n do
        local c = list[i]
        local ax, ay, az, bx, by, bz = endpoints(c)
        if ax then
            push(out, cap(c.uid, c.r, ax + dx, ay + dy, az + dz, bx + dx, by + dy, bz + dz, c.slot))
        end
    end
    return out
end

-- The weapon's capsules as they would sit with the holder's wrist at x,y,z. Same exactness argument as above.
local function gunAt(side, x, y, z, out)
    if WGN == 0 then return out end
    local h = HAND[side]
    if not h then return out end
    local hx, hy, hz = bone(h.index)
    if not hx then return out end
    local dx, dy, dz = x - hx, y - hy, z - hz
    for i = 1, WGN do
        local cx, cy, cz = WGX[i] + dx, WGY[i] + dy, WGZ[i] + dz
        local ex, ey, ez = WGDX[i], WGDY[i], WGDZ[i]
        push(out, cap(GUN_ID + i, WCAPS[i].r,
                      cx - ex, cy - ey, cz - ez, cx + ex, cy + ey, cz + ez, WCAPS[i].bone))
    end
    return out
end

-- Translate a RIGID SET of capsules until none of them overlaps any obstacle, and return the translation.
local function resolveRig(side, movers, segs)
    if movers.n == 0 or segs.n == 0 then return 0.0, 0.0, 0.0 end
    local mem = stick[side]
    local tx, ty, tz = 0.0, 0.0, 0.0

    -- COARSE CULL: one sphere test per obstacle against the whole mover set. The pairwise pass below is
    -- movers x obstacles -- 74 x 90 with fingers and a 58-capsule weapon -- and no amount of slack tuning
    -- changes that product; measured, tightening the pairwise slack from 0.15 to 0.05 moved the pair count from
    -- 722 to 806, because the weapon had meanwhile gone from 28 capsules to 58. Culling the obstacles once does
    -- change it. Grown by CULL because this list is built once and must survive the whole hold, measured as far
    -- as 0.166 m.
    NEAR.n = 0
    local cx, cy, cz = 0.0, 0.0, 0.0
    for i = 1, movers.n do
        local m = movers[i]
        cx, cy, cz = cx + m.cx, cy + m.cy, cz + m.cz
    end
    local inv = 1.0 / movers.n
    cx, cy, cz = cx * inv, cy * inv, cz * inv
    local rad = 0.0
    for i = 1, movers.n do
        local m = movers[i]
        local dx, dy, dz = m.cx - cx, m.cy - cy, m.cz - cz
        local d = math.sqrt(dx * dx + dy * dy + dz * dz) + m.e
        if d > rad then rad = d end
    end
    rad = rad + CULL
    for i = 1, segs.n do
        local s = segs[i]
        local dx, dy, dz = s.cx - cx, s.cy - cy, s.cz - cz
        local reach = rad + s.e
        if dx * dx + dy * dy + dz * dz <= reach * reach then push(NEAR, s) end
    end
    if NEAR.n == 0 then return 0.0, 0.0, 0.0 end

    local n = 0
    local function broadphase()
        n = 0
        for mi = 1, movers.n do
            local m = movers[mi]
            local mx, my, mz = m.cx + tx, m.cy + ty, m.cz + tz
            local me, mid = m.e, m.id * 512
            for si = 1, NEAR.n do
                local s = NEAR[si]
                local dx, dy, dz = mx - s.cx, my - s.cy, mz - s.cz
                local reach = me + s.e + BROAD
                if dx * dx + dy * dy + dz * dz <= reach * reach then
                    n = n + 1
                    CD_M[n], CD_S[n], CD_KEY[n] = m, s, mid + s.id
                end
            end
        end
        if n > candMax then candMax = n end
        return n
    end

    if broadphase() == 0 then return 0.0, 0.0, 0.0 end
    local bx, by, bz = 0.0, 0.0, 0.0

    for _ = 1, PASSES do
        -- SEQUENTIAL PROJECTION: each contact is answered in full the moment it is found, and the next one is
        -- evaluated against the already-moved rig. Count-independent, unlike an average -- see cause 4.
        local deepest, dm, ds = 0.0, nil, nil
        for ci = 1, n do
            local m, s, key = CD_M[ci], CD_S[ci], CD_KEY[ci]
            local hx, hy, hz, qx, qy, qz = segClosest(
                m.ax + tx, m.ay + ty, m.az + tz, m.bx + tx, m.by + ty, m.bz + tz,
                s.ax, s.ay, s.az, s.bx, s.by, s.bz)
            local sx, sy, sz = hx - qx, hy - qy, hz - qz
            local dist = math.sqrt(sx * sx + sy * sy + sz * sz)
            local need = m.r + s.r
            local mm = mem[key]
            local limit = need
            if mm then limit = need + RELEASE_MARGIN end
            if dist >= limit then
                if mm then mem[key] = nil end
            else
                local ux, uy, uz
                if dist > 1e-5 then ux, uy, uz = sx / dist, sy / dist, sz / dist
                else ux, uy, uz = 0.0, 0.0, 1.0 end
                if mm then
                    -- keep leaving by the side it first left by; the shortest way out flips once the mover is
                    -- past the axis, and following that flip teleported the hand through the chest
                    if (mm[1] * ux + mm[2] * uy + mm[3] * uz) < 0.0 then
                        ux, uy, uz = mm[1], mm[2], mm[3]
                        dist = -(sx * ux + sy * uy + sz * uz)
                    end
                else
                    mem[key] = { ux, uy, uz }
                end
                local depth = need - dist
                if depth > 0.0 then
                    local step = depth * OMEGA
                    tx, ty, tz = tx + ux * step, ty + uy * step, tz + uz * step
                    if depth > deepest then deepest, dm, ds = depth, m, s end
                end
            end
        end
        if dm then worstM[side], worstS[side] = dm.label, ds.label end
        if deepest <= SETTLED then break end
        local ddx, ddy, ddz = tx - bx, ty - by, tz - bz
        if ddx * ddx + ddy * ddy + ddz * ddz > BROAD * BROAD * 0.25 then
            bx, by, bz = tx, ty, tz
            if broadphase() == 0 then break end
        end
    end
    return tx, ty, tz
end

-- WHICH HAND HOLDS THE WEAPON, latched for the life of that weapon instance. Decided per frame as "nearer wrist"
-- it flipped whenever the free hand came to the grip -- which is where the trigger is -- and each flip swapped
-- which hand was frozen. A weapon does not change hands while equipped.
local HOLDER_DROP = 0.30    -- m: beyond this from the grip, the latched hand plainly is not holding it
local HOLDER_EDGE = 0.05    -- m: the challenger must be this much nearer before the LEFT hand is believed
local holderSide, holderEnt = nil, nil
local dbgDL, dbgDR = -1.0, -1.0

-- WHICH HAND HOLDS THE GUN, asked of the game rather than guessed from geometry.
--
-- The distance test below picks whichever wrist is nearer the grip, and that is wrong exactly when it matters: a
-- hand reaching for the MAGAZINE passes closer to the grip than the hand holding the weapon. The holder then
-- flipped to the free hand -- the gun visibly snapped across to it ("пистолет встает под левую руку") and the
-- reload's magnet, which always drives the hand that is NOT the holder, started pulling the real gun hand.
--
-- The game already knows the answer: a held weapon is attached to `ItemAttachmentSlots.WeaponRight` or
-- `.WeaponLeft`, and `GetItemInSlot` returns it. Verified live -- the active weapon's entity id came back from
-- WeaponRight and from nowhere else. Cached per weapon, because it cannot change without the weapon changing.
local slotHolder, slotHolderFor = nil, nil
local function holderFromSlot()
    local pl = Game.GetPlayer()
    local w = pl and pl:GetActiveWeapon()
    if not w then slotHolder, slotHolderFor = nil, nil; return nil end
    local okId, wid = pcall(function() return w:GetEntityID().hash end)
    if not okId then return nil end
    if slotHolderFor == wid then return slotHolder end
    local ts = Game.GetTransactionSystem()
    if not ts then return nil end
    local found = nil
    for _, e in ipairs({ { 1, 'AttachmentSlots.WeaponRight' }, { 0, 'AttachmentSlots.WeaponLeft' } }) do
        local ok, it = pcall(function() return ts:GetItemInSlot(pl, TweakDBID.new(e[2])) end)
        if ok and it then
            local ok2, h = pcall(function() return it:GetEntityID().hash end)
            if ok2 and h == wid then found = e[1]; break end
        end
    end
    if found ~= nil then slotHolder, slotHolderFor = found, wid end
    return found
end

local function holderOf(rl, rr)
    -- the game's own answer wins; the geometry below is only for when it has none to give
    local s = holderFromSlot()
    if s ~= nil then
        holderSide, holderEnt = s, slotEnt
        local function d0(v)
            if not v then return -1.0 end
            local dx, dy, dz = v.x - WGRX, v.y - WGRY, v.z - WGRZ
            return math.sqrt(dx * dx + dy * dy + dz * dz)
        end
        dbgDL, dbgDR = d0(rl), d0(rr)
        return s
    end
    if slotEnt ~= holderEnt then holderSide, holderEnt = nil, slotEnt end
    local function dist(v)
        local dx, dy, dz = v.x - WGRX, v.y - WGRY, v.z - WGRZ
        return math.sqrt(dx * dx + dy * dy + dz * dz)
    end
    dbgDL = rl and dist(rl) or -1.0
    dbgDR = rr and dist(rr) or -1.0

    if holderSide ~= nil then
        local d = (holderSide == 0) and dbgDL or dbgDR
        if d >= 0.0 and d <= HOLDER_DROP then return holderSide end
        holderSide = nil
    end

    -- Right by default, and the left has to WIN by a margin. Cyberpunk holds a weapon in the right hand; the
    -- left is only ever a support hand, and it can sit as close to the grip as the right one does. A tie going
    -- the wrong way costs the whole feature, since the true holder then gets pushed off its own weapon.
    if rl and rr then
        holderSide = (dbgDL + HOLDER_EDGE < dbgDR) and 0 or 1
    elseif rr then holderSide = 1
    elseif rl then holderSide = 0 end
    return holderSide
end

local logAcc = 0.0
local PX, PY, PZ = {}, {}, {}      -- the resolved wrist per side, reused
local RAW = {}

-- STAGE TRACER: which point the LAST frame reached and with what inputs, printed once a second from the TOP of
-- onUpdate (before any early return can silence it). Exists because the grip died with zero log output twice, and
-- each time the silent early-out cost a debugging round to even locate.
local dbgStage, dbgAcc, dbgNote = 'never-ran', 0.0, ''

registerForEvent('onUpdate', function(dt)
    dbgAcc = dbgAcc + (dt or 0.016)
    if dbgAcc >= 1.0 then
        dbgAcc = 0.0
        if dbgOn() then
            pcall(function() spdlog.info(string.format('[Tick] stage=%s %s ownHand=%s collOn=%s',
                dbgStage, dbgNote,
                (type(GetVRSharedSlot) == 'function') and tostring(GetVRSharedSlot(162)) or '?',
                tostring(COLL_ON))) end)
        end
    end
    local t0 = (os and os.clock) and os.clock() or nil
    dbgStage, dbgNote = 'natives', ''
    if type(VRHandRawModel) ~= 'function' or type(VRHandStopModel) ~= 'function' then return end
    if type(VRBoneModelPos) ~= 'function' or type(VRBoneModelRot) ~= 'function' then return end
    if type(SetVRDiagCapture) ~= 'function' then return end
    ensureCapture()
    ensureDeadband()
    -- The census is NOT started any more: identification is by bone name in the hook, and the census recorded
    -- every skeleton in the world on the hot path for nothing.
    if not censusStarted then censusStarted, censusAt = true, 0.0 end

    gen = gen + 1
    poolN = 0

    local rl, rr = VRHandRawModel(0), VRHandRawModel(1)
    dbgStage = 'hands'
    dbgNote = string.format('Lw=%.1f Rw=%.1f', rl and rl.w or -1, rr and rr.w or -1)
    if rl and rl.w < 0.5 then rl = nil end
    if rr and rr.w < 0.5 then rr = nil end
    if not rl and not rr then return end
    RAW[0], RAW[1] = rl, rr
    if rl then PX[0], PY[0], PZ[0] = rl.x, rl.y, rl.z end
    if rr then PX[1], PY[1], PZ[1] = rr.x, rr.y, rr.z end

    local holder = nil
    local haveGun = readWeapon() > 0
    if type(VRPoseCensus) == 'function' then VRPoseCensus(-4, haveGun and 1 or 0) end
    if haveGun then
        holder = holderOf(rl, rr)
        if holder ~= nil and (not RAW[holder] or not HAND[holder]) then holder = nil end
    end

    -- COLLISION OFF (dev): release both hands so nothing clamps them, run only the physical reload, and stop.
    if not COLL_ON then
        dbgStage = 'colloff'
        dbgNote = string.format('gun=%s holder=%s slotComp=%s', tostring(haveGun), tostring(holder), tostring(slotComp ~= nil))
        -- ...EXCEPT THE WRIST THE RELOAD HOLDS, and that exception is what the split cost here. While the
        -- reload lived in this file the release was safe by construction: it ran, and the reload's frame
        -- re-took its wrist two statements later in this same callback. Two mods have no guaranteed
        -- callback order, so a release can land AFTER the hold and cancel it -- which is a magnet that
        -- simply does not hold. Same rule the solve path below has always used for the owned wrist.
        local ownRel = nil
        if type(GetVRSharedSlot) == 'function' then
            local v = GetVRSharedSlot(162)
            if v == 0.0 or v == 1.0 then ownRel = math.floor(v) end
        end
        if ownRel ~= 0 then pcall(function() VRHandStopModel(0, false, Vector4.new(0, 0, 0, 0)) end) end
        if ownRel ~= 1 then pcall(function() VRHandStopModel(1, false, Vector4.new(0, 0, 0, 0)) end) end
        -- ALSO WITH THE COLLISION SOLVE OFF. The gun is physical because of its ASSET, not because of this module,
        -- so it blocks the player whether or not the hand clamp is running -- and the log proved the pass never fired
        -- for exactly that reason: it sat past this early exit, and `collOn=false` takes it every frame.
        weaponQueriesOff(lastW, os.clock())
        if not bodyCapsulesForVehicle(os.clock()) then bodyQueriesOff(os.clock()) end
        return
    end

    
-- THE HAND THE RELOAD OWNS. While it glues a wrist to a weapon part (the slide's grip, the magazine's magnet) that
    -- wrist has exactly one writer -- the reload's -- and this solve must neither push it nor publish it. Two writers
    -- on one wrist is a shake, not a compromise: this module publishes a push-OUT of the gun every frame and the
    -- reload then writes its own hold over it, so the pin is dropped and re-taken frame after frame. And leaving the
    -- owned hand out of the solve is the same rule that killed the first shake -- nothing an IK solve places may be an
    -- obstacle for it -- since the reload deliberately holds that hand against the very part this would push it off.
    -- The flag is one frame old (the reload runs in its own mod, after this one): right, because ownership
    -- changes at the speed of a hand.
    --
    -- THROUGH SHARED SLOT [162], which is what the split cost. Two CET mods are two sandboxes and cannot see each
    -- other's tables, so the reload publishes the wrist it owns (SetVRReloadOwnedHand) and this reads it. -1 means
    -- nobody owns a wrist -- including when the reload mod is not installed at all, which is the point: this module
    -- now runs without it.
    local ownHand = nil
    if type(GetVRSharedSlot) == 'function' then
        local v = GetVRSharedSlot(162)
        if v == 0.0 or v == 1.0 then ownHand = math.floor(v) end
    end

    if holder ~= nil then
        -- 1. THE HOLDER: its hand, its fingers and the whole gun, against the body. Placed from the RAW wrist, so
        --    this step depends on nothing but tracking, which is what lets the gun be pushed at all without the
        --    shake coming back.
        local h = RAW[holder]
        LA.n = 0
        ridingSet(holder, h.x, h.y, h.z, LA)
        gunAt(holder, h.x, h.y, h.z, LA)
        local dx, dy, dz = resolveRig(holder, LA, buildObstacles(holder, LB))
        PX[holder], PY[holder], PZ[holder] = h.x + dx, h.y + dy, h.z + dz

        -- 2. THE FREE HAND: against the body, against the gun where step 1 just put it, and against the holder's
        --    hand and fingers. One sequential solve over all three, so the answer satisfies them together.
        local free = 1 - holder
        local f = RAW[free]
        if f and HAND[free] and free ~= ownHand then
            buildObstacles(free, LB)
            gunAt(holder, PX[holder], PY[holder], PZ[holder], LB)
            ridingSet(holder, PX[holder], PY[holder], PZ[holder], LB)
            LA.n = 0
            ridingSet(free, f.x, f.y, f.z, LA)
            local ex, ey, ez = resolveRig(free, LA, LB)
            PX[free], PY[free], PZ[free] = f.x + ex, f.y + ey, f.z + ez
        elseif f then
            PX[free], PY[free], PZ[free] = f.x, f.y, f.z    -- the reload owns it: leave it exactly where tracking says
        end
    else
        -- 3. NO WEAPON: each hand against the body, then hand against hand.
        for side = 0, 1 do
            local r0 = RAW[side]
            if r0 and HAND[side] then
                LA.n = 0
                ridingSet(side, r0.x, r0.y, r0.z, LA)
                local dx, dy, dz = resolveRig(side, LA, buildObstacles(side, LB))
                PX[side], PY[side], PZ[side] = r0.x + dx, r0.y + dy, r0.z + dz
            end
        end
        -- Fingers and all: solve the left set against the right set held still, then split the answer between
        -- them. Both are placed from positions that are pure functions of tracking, so this cannot ring, and half
        -- each is what two equal masses meeting would do -- pushing only one would make the same gesture behave
        -- differently depending on which hand you moved.
        if rl and rr and HAND[0] and HAND[1] then
            LA.n = 0; LB.n = 0
            ridingSet(0, PX[0], PY[0], PZ[0], LA)
            ridingSet(1, PX[1], PY[1], PZ[1], LB)
            local dx, dy, dz = resolveRig(0, LA, LB)
            PX[0], PY[0], PZ[0] = PX[0] + dx * 0.5, PY[0] + dy * 0.5, PZ[0] + dz * 0.5
            PX[1], PY[1], PZ[1] = PX[1] - dx * 0.5, PY[1] - dy * 0.5, PZ[1] - dz * 0.5
        end
    end

    -- Publishing, with a limit and a soft release. Past MAX_HOLD the drawn hand is so far from the real one that
    -- keeping it there is worse than letting go -- but letting go in one frame is the snap that reads as a
    -- teleport, so the hold is faded out over RELEASE seconds instead.
    local function send(side)
        if ownHand == side then
            smooth[side], lastStep[side] = nil, nil    -- no accumulated hold to carry back when we take it again
            return 0.0
        end
        local r0 = RAW[side]
        if not r0 then
            VRHandStopModel(side, false, Vector4.new(0, 0, 0, 0))
            smooth[side], lastStep[side] = nil, nil
            return 0.0
        end
        local ox, oy, oz = PX[side] - r0.x, PY[side] - r0.y, PZ[side] - r0.z
        local prev = smooth[side]
        if prev then
            local sx, sy, sz = ox - prev[1], oy - prev[2], oz - prev[3]
            -- SIGN-FLIP DAMPER. A hold whose change reverses direction from one frame to the next is ringing,
            -- not motion, so only part of it is taken; a steady push never reverses and pays nothing.
            local ls = lastStep[side]
            if ls and (sx * ls[1] + sy * ls[2] + sz * ls[3]) < 0.0 then
                sx, sy, sz = sx * 0.35, sy * 0.35, sz * 0.35
                flips[side] = flips[side] + 1
            end
            ls = ls or {}
            ls[1], ls[2], ls[3] = sx, sy, sz
            lastStep[side] = ls
            local k = 1.0 - math.exp(-(dt or 0.016) / SMOOTH_TAU)
            ox, oy, oz = prev[1] + sx * k, prev[2] + sy * k, prev[3] + sz * k
        else
            lastStep[side] = nil
        end
        prev = prev or {}
        prev[1], prev[2], prev[3] = ox, oy, oz
        smooth[side] = prev

        local off = math.sqrt(ox * ox + oy * oy + oz * oz)
        if off > MAX_HOLD then fade[side] = RELEASE end
        local kf = 1.0
        if fade[side] > 0.0 then
            fade[side] = fade[side] - (dt or 0.016)
            kf = math.max(0.0, fade[side]) / RELEASE
            off = off * kf
        end
        VRHandStopModel(side, off > DEAD,
            Vector4.new(r0.x + ox * kf, r0.y + oy * kf, r0.z + oz * kf, 1.0))
        return off
    end

    local offL, offR = send(0), send(1)

    -- the gun is physical for props, invisible to the movement system (see weaponQueriesOff)
    weaponQueriesOff(lastW, os.clock())
    -- and the body capsules are switched off entirely while mounted -- see bodyCapsulesForVehicle
    if not bodyCapsulesForVehicle(os.clock()) then bodyQueriesOff(os.clock()) end

    if t0 then
        local ms = (os.clock() - t0) * 1000.0
        msAcc, msN = msAcc + ms, msN + 1
        if ms > msMax then msMax = ms end
    end

    logAcc = logAcc + (dt or 0.016)
    if logAcc >= 1.0 and dbgOn() then
        logAcc = 0.0
        pcall(function()
            spdlog.info(string.format(
                "[HandColl] holder=%s (grip L=%.3f R=%.3f) caps=%d w=%s slots=%s gun=%d miss=%d pairs<=%d pool=%d solve %.2f/%.2f ms | held L=%.3f R=%.3f"
                .. " | stopped by L=%s>%s R=%s>%s | reversals/s L=%d R=%d",
                tostring(holder), dbgDL, dbgDR, #CAPS,
                lastW and 'yes' or 'no', slotComp and 'yes' or 'no', WGN, wMiss, candMax, poolN,
                (msN > 0) and (msAcc / msN) or -1.0, msMax, offL, offR,
                tostring(worstM[0]), tostring(worstS[0]), tostring(worstM[1]), tostring(worstS[1]),
                flips[0], flips[1]))
        end)
        -- THE RELOAD GATE. Parts whose local translation is moving are the ones the reload animation drives, and
        -- those are exactly the ones a physical reload has to write.
        -- THE CENSUS, reported so the weapon's rigs can be picked out by eye once: entries that only exist
        -- while a gun is in hand, with a small hit count each (four rigs, a few passes a tick).
        if type(VRPoseCensus) == 'function' and censusAt then
            pcall(function()
                -- The two rigs, nominated by the (bones, tracks) pair the pose descriptor carries and
                -- checked against the rig assets: 16 bones and 0 tracks for the frame, 5 and 2 for the magazine.
                local rows = {}
                for w = 0, 1 do
                    rows[#rows + 1] = string.format('%s seen=%d bones=%d tracks=%d buf=%08X%08X',
                        (w == 0) and 'mag' or 'frame',
                        VRRigStatus(0 + w), VRRigStatus(2 + w), VRRigStatus(4 + w),
                        VRRigStatus(8 + w), VRRigStatus(6 + w))
                end
                spdlog.info(string.format("[Rig] weapon=%s | %s",
                    (WGN > 0) and 'yes' or 'no', table.concat(rows, ' | ')))
            end)
        end
        flips[0], flips[1] = 0, 0
        worstM[0], worstS[0], worstM[1], worstS[1] = '-', '-', '-', '-'
        candMax = 0
        msAcc, msMax, msN = 0.0, 0.0, 0
    end
end)

-- The reload recorder lives in its OWN mod (CyberpunkVRPort_ReloadRecorder). CET keeps ONE callback per
-- event per mod, and hosting the recorder's onUpdate here silently replaced the main loop above -- the
-- dead-grip bug that cost three sessions. Never host a second per-frame job in this file.

-- ---------------------------------------------------------------------------------------------------------
-- MAGAZINE TUNER, in the CET overlay.
--
-- Every constant in a weapon config is measured, and it stays that way -- but the game's hand RE-GRIPS the
-- magazine on the way in (measured: its origin sits 4.3-6.7 cm from the hold slot while it is pushed home and
-- 12.5 cm at the frame it seats, and that last one is already after the hand let go). A VR hand holds one
-- relation, so exactly one number here cannot come from the animation: which of them to wear. This window is
-- where that gets decided by the eye that has to look at it, and PRINTED, so it goes back into the config as a
-- constant beside the measured ones rather than living as a slider forever.

registerForEvent('onShutdown', function()
    pcall(function() VRHandStopModel(0, false, Vector4.new(0, 0, 0, 0)) end)
    pcall(function() VRHandStopModel(1, false, Vector4.new(0, 0, 0, 0)) end)
    -- the wrist rotation lock is plugin-side state; left on through a mod reload it would freeze the hand's aim
    pcall(function() VRHandStopRot(0, 0, 0, 0, 0, 1) end)
    pcall(function() VRHandStopRot(1, 0, 0, 0, 0, 1) end)
    pcall(function() VRHandStopDeadband(0.02) end)   -- leave the plugin as it ships
end)
